### ISSUE TITLE
Attribute parser: SourceFile

### ISSUE THREAD

**Issue by Palmr** [Palmr/classfile-parser#10]
A parser is required for SourceFile attributes

https://docs.oracle.com/javase/specs/jvms/se8/html/jvms-4.html#jvms-4.7.10

**Comment by Alfriadox** [comment]
Hello! Can I work on this?

**Comment by Palmr** [comment]
Of course, all pull requests are welcome :)

**Comment by Alfriadox** [comment]
I made a pr for this.

**Comment by Palmr** [comment]
Yeah, will mark this as resolved since PR #15
