### ISSUE TITLE
Handling of unpaired Unicode surrogates

### ISSUE THREAD

**Issue by george-hopkins** [Palmr/classfile-parser#20]
Now that the parsing of valid Java strings works as expected (thanks!), I discovered an other issue: Java supports [unpaired surrogates](https://en.wikipedia.org/wiki/UTF-16#U+D800_to_U+DFFF) (`U+D800` to `U+DFFF`). They aren't officially allowed, which is why Rust does not support them. However, some Java libraries use them to encode binary data (e.g. [libgcj](http://cvs.savannah.gnu.org/viewvc/gnu-crypto/gnu-crypto/gcj/source/gnu/crypto/cipher/Square.java?view=markup#l83)). At the moment, `class_parser` is unable to handle such classes because the decoding error is propagated back to it.

Possible solutions:
* keep as is
* change `utf8_string` to `Result<String, Vec<u8>>` and let the user decide (e.g. apply [`String::from_utf8_lossy`](https://doc.rust-lang.org/std/string/struct.String.html#method.from_utf8_lossy))
* apply `String::from_utf8_lossy` ourselves
* ...

**Comment by Palmr** [comment]
I think whatever type we return for *utf8* constants there should be a way to get a Vec<u8> from it which exactly matches the Vec<u8> for the constant.

Potentially the Utf8Constant struct should contain utf8_string being a string parsed with String::from_utf8_lossy for convenience as well as the original Vec<u8> to be used at the consumers discretion?

```rust
pub struct Utf8Constant {
    pub utf8_string: String,
    pub bytes: Vec<u8>,
}
```

**Comment by Palmr** [comment]
Fix merged in. Thanks @george-hopkins
